// I/O Errors
#define ERR_FILE_PARTITE_INESISTENTE 1
#define ERR_FILE_IMP_INESISTENTE 2
#define ERR_FILE_REC_INESISTENTE 3
#define ERR_FILE_AIUTO_INESISTENTE 4
#define ERR_FILE_IMP_INVALID 5
#define ERR_IMP_INVALID 6
#define ERR_FILE_AIUTO_VUOTO 7
#define ERR_PARTITA_NON_INIZIATA 8
#define ERR_FILE_PARTITE_VUOTO 9
#define ERR_FILE_REC_VUOTO 10
#define ERR_FILE_IMP_VUOTO 12
#define ERR_IMP_INESISTENTE 13

// Gameplay errors
#define ERR_CASELLA_INESISTENTE 100
#define ERR_CASELLA_PIENA 101
#define ERR_CASELLA_VUOTA 102
#define ERR_CASELLE_NON_ADIACENTI 103
#define ERR_PEDINA_AVVERSARIA 104
#define ERR_PEDINA_GIOCATORE_TURNO 105
#define ERR_INTERROTTA 106
#define ERR_MULINO 107

void Gestione_Errori(int errore);
